### ISSUE TITLE
Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.10 and higher. do not satisfy the required version:

### ISSUE THREAD

**Issue by sagarshende23** [sbis04/flutter_os_wear#1]
![App build gradle](https://user-images.githubusercontent.com/43273993/72218515-789ee300-3561-11ea-8d88-44ecfe752c72.jpg)
![build gradle](https://user-images.githubusercontent.com/43273993/72218516-7b013d00-3561-11ea-94d1-003338642347.jpg)
![gradle wrapper](https://user-images.githubusercontent.com/43273993/72218562-e6e3a580-3561-11ea-83bd-6e6d9edb1e7d.jpg)

Error Showing in debug Console 
![error](https://user-images.githubusercontent.com/43273993/72218519-7e94c400-3561-11ea-8592-cfcd3d53f7fa.jpg)

Flutter v1.12.13+hotfix.5 (Newest Version)

**Comment by sbis04** [comment]
# Fixes
This was a plugin related error for [flutter_wear_plugin](https://github.com/mjohnsullivan/flutter_wear_plugin), as it is not maintained for a long period of time. The plugin version **0.0.3** currently does not support **AndroidX** and the **dependencies** are very old, which was causing the error. 

I have removed the plugin and added all the code in the same app, but the channels are not set up properly now. I will try to fix all the things by next week. 

# Limitations:
The **Ambient Display** will not work as the channel is not set up still now.

# flutter_wear_plugin
There is already a pull request sent to the plugin source  code but it has not been merged still now: https://github.com/mjohnsullivan/flutter_wear_plugin/pull/5
